[theme]
base = "dark"
primaryColor = "#ff4b4b"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#262730"
textColor = "#fafafa"

[global]
developmentMode = false

[server]
headless = true
port = 8501
enableXsrfProtection = false
address = "localhost"

[browser]
gatherUsageStats = false