name: Windows Testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install uv
      run: |
        pip install uv
    
    - name: Install dependencies
      run: |
        uv pip install -r requirements.txt --system
    
    - name: Test Streamlit app import
      run: |
        python -c "import sys; sys.path.append('app'); import streamlit_app; print('Streamlit app imports successfully')"
    
    - name: Run Streamlit app (smoke test)
      run: |
        start /b streamlit run app/streamlit_app.py --server.headless true --server.port 8501
        timeout /t 10
        curl -f http://localhost:8501 && echo "Streamlit started successfully" || echo "Streamlit failed to start"
      shell: cmd
    
    - name: Check for Windows-specific issues
      run: |
        python -c "
        import os
        import sys
        print(f'Python version: {sys.version}')
        print(f'Platform: {sys.platform}')
        print(f'Working directory: {os.getcwd()}')
        print('Windows compatibility check passed')
        "